//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodcorner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminOrderDetail
    {
        public int OrderId { get; set; }
        public int SuppItemId { get; set; }
        public int Paymnet { get; set; }
    
        public virtual AdminOrder AdminOrder { get; set; }
        public virtual SupplierItem SupplierItem { get; set; }
    }
}
