//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodcorner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignOrder
    {
        public int DelivererId { get; set; }
        public int OrderId { get; set; }
        public Nullable<double> DeliveryTime { get; set; }
        public string Status { get; set; }
    
        public virtual DeliveryTeam DeliveryTeam { get; set; }
        public virtual PlaceOrder PlaceOrder { get; set; }
    }
}
