//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodcorner.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB22Entities3 : DbContext
    {
        public DB22Entities3()
            : base("name=DB22Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminOrder> AdminOrders { get; set; }
        public virtual DbSet<AdminOrderDetail> AdminOrderDetails { get; set; }
        public virtual DbSet<AssignOrder> AssignOrders { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Chef> Chefs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryTeam> DeliveryTeams { get; set; }
        public virtual DbSet<ItemsDetail> ItemsDetails { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<PassOrder> PassOrders { get; set; }
        public virtual DbSet<PlaceOrder> PlaceOrders { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierCategory> SupplierCategories { get; set; }
        public virtual DbSet<SupplierItem> SupplierItems { get; set; }
    }
}
